knpu_oauth2_client:
    clients:
        keycloak:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            client_id: '%env(OAUTH_KEYCLOAK_ID)%'
            client_secret: '%env(OAUTH_KEYCLOAK_SECRET)%'
            redirect_route: connect_keycloak_check
            redirect_params: {}
            provider_options:
                urlAuthorize: 'https://id.projecttick.net/realms/projecttick/protocol/openid-connect/auth'
                urlAccessToken: 'https://id.projecttick.net/realms/projecttick/protocol/openid-connect/token'
                urlResourceOwnerDetails: 'https://id.projecttick.net/realms/projecttick/protocol/openid-connect/userinfo'
                scopes: ['openid', 'email', 'profile']
